### PR TITLE
fix for issue #2

### PR DESCRIPTION
**Pull request by chennanxu**
The DTNHost.java call a function which doesn't exist.

### CODE REVIEW

**Comment by ilmanss** [comment]
Thank You so much @chennanxu.
Now no error when i compile it.

But when i run ./one.sh it got new error:

root@ubuntu:/home/onesim/Downloads/the-one-pitt-master# ./one.sh 
Error: Could not find or load main class core.DTNSim

Do you know why this problem?
Thank you

**Comment by chennanxu** [comment]
@ilmanss You can replace the original one.sh with the following content
#! /bin/sh
java -Xmx512M -cp .:target:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $*

But there is still some confusing problems in this version.My suggestion is to copy the file you need to the latest version of ONE.

I hope it will be helpful.

**Comment by ilmanss** [comment]
Thank for answer @chennanxu 

Well actually i was import georouter.java to original ONE and fix the error, but when i run with my scenario i get another error (maybe need another file) like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./one.sh mnode30.txt
Can't start: error in configuration file(s)
Can't find setting 'GeoRouter.maxVRArea'

and after that when i compile again i get new error like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./compile.bat 
routing/GeoRouter.java:67: error: cannot find symbol
		int[] vrAreaSize = s.getCsvInts(MAX_VR_AREA_S);
		                                ^
  symbol:   variable MAX_VR_AREA_S
  location: class GeoRouter
1 error

Do you know how to fix that? @chennanxu 
Thank You for help

**Comment by ilmanss** [comment]
Thank for answer @chennanxu

Well actually i was import georouter.java to original ONE and fix the error, but when i run with my scenario i get another error (maybe it need another file) like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./one.sh mnode30.txt
Can't start: error in configuration file(s)
Can't find setting 'GeoRouter.maxVRArea'

and after that when i compile again i get new error like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./compile.bat
routing/GeoRouter.java:67: error: cannot find symbol
int[] vrAreaSize = s.getCsvInts(MAX_VR_AREA_S);
^
symbol: variable MAX_VR_AREA_S
location: class GeoRouter
1 error

Do you know how to fix that? @chennanxu
Thank You for help

**Comment by ilmanss** [comment]
Thank for answer @chennanxu

Well actually i was import georouter.java to original ONE and fix the error, but when i run with my scenario i get another error (maybe it need another file) like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./one.sh mnode30.txt
Can't start: error in configuration file(s)
Can't find setting 'GeoRouter.maxVRArea'

and after that when i compile again i get new error like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./compile.bat
routing/GeoRouter.java:67: error: cannot find symbol
int[] vrAreaSize = s.getCsvInts(MAX_VR_AREA_S);
                                                 ^
symbol: variable MAX_VR_AREA_S
location: class GeoRouter
1 error

Do you know how to fix that? @chennanxu
Thank You for help

**Comment by ilmanss** [comment]
Thank for answer @chennanxu

Well actually i was import georouter.java to original ONE and fix the error, but when i run with my scenario i get another error (maybe it need another file) like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./one.sh mnode30.txt
Can't start: error in configuration file(s)
Can't find setting 'GeoRouter.maxVRArea'

and after that when i compile again i get new error like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./compile.bat
routing/GeoRouter.java:67: error: cannot find symbol
int[] vrAreaSize = s.getCsvInts(MAX_VR_AREA_S);
                                                 ^
symbol: variable MAX_VR_AREA_S
location: class GeoRouter
1 error

Do you know how to fix that? @chennanxu
Thank You for help

**Comment by ilmanss** [comment]
Thank for answer @chennanxu

Well actually i was import georouter.java to original ONE and fix the error, but when i run with my scenario i get another error (maybe it need another file) like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./one.sh mnode30.txt
Can't start: error in configuration file(s)
Can't find setting 'GeoRouter.maxVRArea'

and after that when i compile again i get new error like this

root@ubuntu:/home/onesimulator/Downloads/one_1.4.1# ./compile.bat
routing/GeoRouter.java:67: error: cannot find symbol
int[] vrAreaSize = s.getCsvInts(MAX_VR_AREA_S);
^
symbol: variable MAX_VR_AREA_S
location: class GeoRouter
1 error

here the screeshot:
screenshot from 2017-09-13 08 10 45

Do you know how to fix that? @chennanxu
Thank You for help

**Comment by chennanxu** [comment]
@ilmanss sorry , I don't know.Because MAX_VR_AREA_S is a variable in the class GeoRouter, the situation you met is confusing.

**Comment by prinkskam** [comment]
root@lappy:~/one_1.5.1-RC2$ ./ one.sh

Error: Could not find or load main class core.DTNSim
I am facing this problem . Could anyone please help me out in this.??

**Review by knightcode — APPROVED** [review]

**Pull request merged**
